# PEC 2

In [1]:
import sys
sys.path.append("..")
import sympy as sp
from sympy.plotting import plot as symplot
import pandas as pd
import numpy as np
from numpy import linspace
import matplotlib.pyplot as plt
from IPython.display import Math, Latex, Markdown

## Solve matrix I using Crout's method

In [2]:
from lu.crout import crout
from lu.solver import lu_solver
import numpy as np

In [3]:
I = np.array([[1, -1, 0, 0, -1, 0, 0],
             [-1, 0, 1, 0, 0, 0, 1],
             [0, 1, 0, -1, 0, 1, 0],
             [1, 0, 0, 0, 5, 0, 5],
             [0, -3, 0, 0, 5, 5, 0],
             [0, 0, -10, 0, 0, 0, 5],
             [0, 0, 0, 10, 0, 5, 0]
             ])

In [4]:
I

array([[  1,  -1,   0,   0,  -1,   0,   0],
       [ -1,   0,   1,   0,   0,   0,   1],
       [  0,   1,   0,  -1,   0,   1,   0],
       [  1,   0,   0,   0,   5,   0,   5],
       [  0,  -3,   0,   0,   5,   5,   0],
       [  0,   0, -10,   0,   0,   0,   5],
       [  0,   0,   0,  10,   0,   5,   0]])

In [5]:
L, U = crout(7, I)

In [6]:
np.set_printoptions(linewidth=100)
print('L matrix:')
print(L)

print('U matrix')
print(U)

L matrix:
[[  1.           0.           0.           0.           0.           0.           0.        ]
 [ -1.          -1.           0.           0.           0.           0.           0.        ]
 [  0.           1.           1.           0.           0.           0.           0.        ]
 [  1.           1.           1.           1.           0.           0.           0.        ]
 [  0.          -3.          -3.          -3.          23.           0.           0.        ]
 [  0.           0.         -10.         -10.          50.         -10.86956522   0.        ]
 [  0.           0.           0.          10.         -60.          28.04347826  72.7       ]]
U matrix
[[ 1.         -1.          0.          0.         -1.          0.          0.        ]
 [ 0.          1.         -1.         -0.          1.         -0.         -1.        ]
 [ 0.          0.          1.         -1.         -1.          1.          1.        ]
 [ 0.          0.          0.          1.          6.        

In [7]:
b = np.array([0, 0, 0, 5, 10, 10, 10])

In [8]:
y, x = lu_solver(L, U, b, 7)

In [9]:
y

array([ 0.        , -0.        ,  0.        ,  5.        ,  1.08695652, -0.52      ,  0.5474553 ])

In [10]:
x

array([-0.17881706, -0.66712517, -0.72627235,  0.44429161,  0.48830812,  1.11141678,  0.5474553 ])

In [11]:
np.matmul(I, x)

array([ 0.,  0.,  0.,  5., 10., 10., 10.])

## Solve matrix I' using Crout's method for tridiagonal matrices

In [12]:
from lu.crout import crout_tridiagonal
import numpy as np

In [13]:
I_prime = np.array([[10, 5, 0, 0, 0, 0, 0],
                   [-1, 1, 1, 0, 0, 0, 0],
                   [0, 5, -3, 5, 0, 0, 0],
                   [0, 0, -1, -1, 1, 0, 0],
                   [0, 0, 0, 5, 1, 5, 0],
                   [0, 0, 0, 0, 1, -1, -1],
                   [0, 0, 0, 0, 0, 5, -10]])

In [14]:
I_prime

array([[ 10,   5,   0,   0,   0,   0,   0],
       [ -1,   1,   1,   0,   0,   0,   0],
       [  0,   5,  -3,   5,   0,   0,   0],
       [  0,   0,  -1,  -1,   1,   0,   0],
       [  0,   0,   0,   5,   1,   5,   0],
       [  0,   0,   0,   0,   1,  -1,  -1],
       [  0,   0,   0,   0,   0,   5, -10]])

In [15]:
L, U = crout_tridiagonal(7, I_prime)

In [16]:
np.set_printoptions(linewidth=100)
print('L matrix:')
print(L)

print('U matrix')
print(U)

L matrix:
[[ 10.           0.           0.           0.           0.           0.           0.        ]
 [ -1.           1.5          0.           0.           0.           0.           0.        ]
 [  0.           5.          -6.33333333   0.           0.           0.           0.        ]
 [  0.           0.          -1.          -1.78947368   0.           0.           0.        ]
 [  0.           0.           0.           5.           3.79411765   0.           0.        ]
 [  0.           0.           0.           0.           1.          -2.31782946   0.        ]
 [  0.           0.           0.           0.           0.           5.         -12.15719064]]
U matrix
[[ 1.          0.5         0.          0.          0.          0.          0.        ]
 [ 0.          1.          0.66666667  0.          0.          0.          0.        ]
 [ 0.          0.          1.         -0.78947368  0.          0.          0.        ]
 [ 0.          0.          0.          1.         -0.55882353

In [17]:
b = np.array([10, 0, 10, 0, 5, 0, 10])

In [18]:
y, x = lu_solver(L, U, b, 7)

In [19]:
y

array([ 1.        ,  0.66666667, -1.05263158,  0.58823529,  0.54263566,  0.23411371, -0.72627235])

In [20]:
x

array([ 0.44429161,  1.11141678, -0.66712517,  0.48830812, -0.17881706,  0.5474553 , -0.72627235])

In [21]:
np.matmul(I_prime, x)

array([ 1.00000000e+01,  0.00000000e+00,  1.00000000e+01, -5.55111512e-17,  5.00000000e+00,
        1.11022302e-16,  1.00000000e+01])

## Solve matrix I' using Doolitle's method

In [22]:
from lu.doolittle import doolittle
import numpy as np
from lu.solver import lu_solver

In [23]:
I_prime = np.array([[10, 5, 0, 0, 0, 0, 0],
                   [-1, 1, 1, 0, 0, 0, 0],
                   [0, 5, -3, 5, 0, 0, 0],
                   [0, 0, -1, -1, 1, 0, 0],
                   [0, 0, 0, 5, 1, 5, 0],
                   [0, 0, 0, 0, 1, -1, -1],
                   [0, 0, 0, 0, 0, 5, -10]])

In [24]:
I_prime

array([[ 10,   5,   0,   0,   0,   0,   0],
       [ -1,   1,   1,   0,   0,   0,   0],
       [  0,   5,  -3,   5,   0,   0,   0],
       [  0,   0,  -1,  -1,   1,   0,   0],
       [  0,   0,   0,   5,   1,   5,   0],
       [  0,   0,   0,   0,   1,  -1,  -1],
       [  0,   0,   0,   0,   0,   5, -10]])

In [25]:
L, U = doolittle(7, I_prime)

In [26]:
np.set_printoptions(linewidth=100)
print('L matrix:')
print(L)

print('U matrix')
print(U)

L matrix:
[[ 1.          0.          0.          0.          0.          0.          0.        ]
 [-0.1         1.          0.          0.          0.          0.          0.        ]
 [ 0.          3.33333333  1.          0.          0.          0.          0.        ]
 [ 0.          0.          0.15789474  1.          0.          0.          0.        ]
 [ 0.          0.         -0.         -2.79411765  1.          0.          0.        ]
 [ 0.          0.         -0.         -0.          0.26356589  1.          0.        ]
 [ 0.          0.         -0.         -0.          0.         -2.15719064  1.        ]]
U matrix
[[ 10.           5.           0.           0.           0.           0.           0.        ]
 [  0.           1.5          1.           0.           0.           0.           0.        ]
 [  0.           0.          -6.33333333   5.           0.           0.           0.        ]
 [  0.           0.           0.          -1.78947368   1.           0.           0.     

In [27]:
b = np.array([10, 0, 10, 0, 5, 0, 10])

In [28]:
y, x = lu_solver(L, U, b, 7)

In [29]:
y

array([10.        ,  1.        ,  6.66666667, -1.05263158,  2.05882353, -0.54263566,  8.82943144])

In [30]:
x

array([ 0.44429161,  1.11141678, -0.66712517,  0.48830812, -0.17881706,  0.5474553 , -0.72627235])

In [31]:
np.matmul(I_prime, x)

array([ 1.00000000e+01,  0.00000000e+00,  1.00000000e+01, -1.66533454e-16,  5.00000000e+00,
        0.00000000e+00,  1.00000000e+01])

## Solve matrix I' using Choleski method

In [2]:
from lu.choleski import choleski
from lu.solver import complex_lu_solver
import numpy as np

In [3]:
I_prime = np.array([[10, 5, 0, 0, 0, 0, 0],
                    [-1, 1, 1, 0, 0, 0, 0],
                    [0, 5, -3, 5, 0, 0, 0],
                    [0, 0, -1, -1, 1, 0, 0],
                    [0, 0, 0, 5, 1, 5, 0],
                    [0, 0, 0, 0, 1, -1, -1],
                    [0, 0, 0, 0, 0, 5, -10]])

In [4]:
I_prime

array([[ 10,   5,   0,   0,   0,   0,   0],
       [ -1,   1,   1,   0,   0,   0,   0],
       [  0,   5,  -3,   5,   0,   0,   0],
       [  0,   0,  -1,  -1,   1,   0,   0],
       [  0,   0,   0,   5,   1,   5,   0],
       [  0,   0,   0,   0,   1,  -1,  -1],
       [  0,   0,   0,   0,   0,   5, -10]])

In [5]:
L = choleski(7, I_prime)

In [6]:
U = np.transpose(L)

In [7]:
np.set_printoptions(linewidth=200)
print('L matrix:')
print(L)

print('U matrix:')
print(U)


L matrix:
[[ 3.16227766+0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j        ]
 [-0.31622777+0.j          0.9486833 +0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          1.05409255+0.j          0.        +2.02758751j  0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        -2.46598481j  2.25412535+0.j          0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j          0.44363105+0.j          0.89620951+0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j          5.57905259+0.j          0.        +5

In [8]:
for k in range(1):
    print(k)

0


In [39]:
b = np.array([10, 0, 10, 0, 5, 0, 10])

In [40]:
y, x = complex_lu_solver(L, U, b, 7)

In [41]:
y = np.linalg.solve(L, b)

In [42]:
np.linalg.solve(U, y)

array([ 1.06133295+0.j,  0.61332947+0.j,  0.44800347+0.j,  2.14613619+0.j, -0.09388118+0.j,  0.589549  +0.j, -1.0589549 -0.j])

In [43]:
np.matmul(L, U)

array([[ 10.+0.j,  -1.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j],
       [ -1.+0.j,   1.+0.j,   1.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j,   1.+0.j,  -3.+0.j,   5.+0.j,   0.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,   5.+0.j,  -1.+0.j,   1.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,   1.+0.j,   1.+0.j,   5.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   5.+0.j,  -1.+0.j,  -1.+0.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,  -1.+0.j, -10.+0.j]])

In [33]:
b_s = np.array(np.matmul(I_prime, x), dtype = np.float)

/Applications/anaconda3/envs/compu/lib/python3.5/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([ 1.36799768e+01, -1.11022302e-16,  1.24533179e+01, -2.68802084e+00,  1.35845448e+01,  3.75524721e-01,  1.35372940e+01])

## Solve matrix I' modified using Choleski method

In [32]:
from lu.choleski import choleski_modified
import numpy as np

In [69]:
I_prime_modified = np.array([[10, 5, 0, 0, 0, 0, 0],
                             [-1, 1, 1, 0, 0, 0, 0],
                             [0, -5, 3, -5, 0, 0, 0],
                             [0, 0, 1, 1, -1, 0, 0],
                             [0, 0, 0, 5, 1, 5, 0],
                             [0, 0, 0, 0, -1, 1, 1],
                             [0, 0, 0, 0, 0, -5, 10]])

In [70]:
I_prime_modified

array([[10,  5,  0,  0,  0,  0,  0],
       [-1,  1,  1,  0,  0,  0,  0],
       [ 0, -5,  3, -5,  0,  0,  0],
       [ 0,  0,  1,  1, -1,  0,  0],
       [ 0,  0,  0,  5,  1,  5,  0],
       [ 0,  0,  0,  0, -1,  1,  1],
       [ 0,  0,  0,  0,  0, -5, 10]])

In [71]:
L, U = choleski_modified(7, I_prime_modified)

In [72]:
np.set_printoptions(linewidth=150)
print('L matrix:')
print(L)

print('U matrix: ')
print(U)

L matrix:
[[ 3.16227766  0.          0.          0.          0.          0.          0.        ]
 [-0.31622777  1.22474487  0.          0.          0.          0.          0.        ]
 [ 0.         -4.0824829   2.51661148  0.          0.          0.          0.        ]
 [ 0.          0.          0.39735971  1.33771211  0.          0.          0.        ]
 [ 0.          0.          0.          3.73772501  1.94784949  0.          0.        ]
 [ 0.          0.          0.          0.         -0.51338669  1.52244194  0.        ]
 [ 0.          0.          0.          0.          0.         -3.28419749  3.48671631]]
U matrix: 
[[ 3.16227766  1.58113883  0.          0.          0.          0.          0.        ]
 [ 0.          1.22474487  0.81649658  0.          0.          0.          0.        ]
 [ 0.          0.          2.51661148 -1.98679854  0.          0.          0.        ]
 [ 0.          0.          0.          1.33771211 -0.747545    0.          0.        ]
 [ 0.          0.    

In [74]:
b = np.array([10, 0, -10, 0, 5, 0, -10])

In [75]:
y, x = lu_solver(L, U, b, 7)

In [76]:
y

array([ 3.16227766,  0.81649658, -2.64906471,  0.78688948,  1.05697259,  0.35642453, -2.53230566])

In [77]:
x

array([ 0.44429161,  1.11141678, -0.66712517,  0.48830812, -0.17881706,  0.5474553 , -0.72627235])

In [78]:
np.matmul(L,U)

array([[10.,  5.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 0., -5.,  3., -5.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  1.,  5.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0., -5., 10.]])