# PEC 2

In [27]:
import sys
sys.path.append("..")
import sympy as sp
from sympy.plotting import plot as symplot
import pandas as pd
import numpy as np
import array_to_latex as a2l
from numpy import linspace
import matplotlib.pyplot as plt
from IPython.display import Math, Latex, Markdown

## Solve matrix I using Crout's method

In [28]:
from lu.crout import crout
from lu.solver import lu_solver
import numpy as np

In [29]:
I = np.array([[1, -1, 0, 0, -1, 0, 0],
             [-1, 0, 1, 0, 0, 0, 1],
             [0, 1, 0, -1, 0, 1, 0],
             [1, 0, 0, 0, 5, 0, 5],
             [0, -3, 0, 0, 5, 5, 0],
             [0, 0, -10, 0, 0, 0, 5],
             [0, 0, 0, 10, 0, 5, 0]
             ])

In [30]:
I

array([[  1,  -1,   0,   0,  -1,   0,   0],
       [ -1,   0,   1,   0,   0,   0,   1],
       [  0,   1,   0,  -1,   0,   1,   0],
       [  1,   0,   0,   0,   5,   0,   5],
       [  0,  -3,   0,   0,   5,   5,   0],
       [  0,   0, -10,   0,   0,   0,   5],
       [  0,   0,   0,  10,   0,   5,   0]])

In [31]:
a2l.to_ltx(I, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    1.00 &  -1.00 &    0.00 &    0.00 &  -1.00 &    0.00 &    0.00\\
  -1.00 &    0.00 &    1.00 &    0.00 &    0.00 &    0.00 &    1.00\\
    0.00 &    1.00 &    0.00 &  -1.00 &    0.00 &    1.00 &    0.00\\
    1.00 &    0.00 &    0.00 &    0.00 &    5.00 &    0.00 &    5.00\\
    0.00 &  -3.00 &    0.00 &    0.00 &    5.00 &    5.00 &    0.00\\
    0.00 &    0.00 & -10.00 &    0.00 &    0.00 &    0.00 &    5.00\\
    0.00 &    0.00 &    0.00 &   10.00 &    0.00 &    5.00 &    0.00
\end{array}


In [32]:
L, U = crout(7, I)

134


In [33]:
np.set_printoptions(linewidth=100)
print('L matrix:')
print(L)

print('U matrix')
print(U)

L matrix:
[[  1.           0.           0.           0.           0.           0.           0.        ]
 [ -1.          -1.           0.           0.           0.           0.           0.        ]
 [  0.           1.           1.           0.           0.           0.           0.        ]
 [  1.           1.           1.           1.           0.           0.           0.        ]
 [  0.          -3.          -3.          -3.          23.           0.           0.        ]
 [  0.           0.         -10.         -10.          50.         -10.86956522   0.        ]
 [  0.           0.           0.          10.         -60.          28.04347826  72.7       ]]
U matrix
[[ 1.         -1.          0.          0.         -1.          0.          0.        ]
 [ 0.          1.         -1.         -0.          1.         -0.         -1.        ]
 [ 0.          0.          1.         -1.         -1.          1.          1.        ]
 [ 0.          0.          0.          1.          6.        

In [34]:
a2l.to_ltx(U, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    1.00 &  -1.00 &    0.00 &    0.00 &  -1.00 &    0.00 &    0.00\\
    0.00 &    1.00 &  -1.00 &   -0.00 &    1.00 &   -0.00 &  -1.00\\
    0.00 &    0.00 &    1.00 &  -1.00 &  -1.00 &    1.00 &    1.00\\
    0.00 &    0.00 &    0.00 &    1.00 &    6.00 &  -1.00 &    5.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    1.00 &    0.22 &    0.65\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    1.00 &  -2.98\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    1.00
\end{array}


In [35]:
b = np.array([0, 0, 0, 5, 10, 10, 10])
a2l.to_ltx(b, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    0.00 &    0.00 &    0.00 &    5.00 &   10.00 &   10.00 &   10.00
\end{array}


In [36]:
y, x = lu_solver(L, U, b, 7)

In [37]:
a2l.to_ltx(y, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    0.00 &   -0.00 &    0.00 &    5.00 &    1.09 &  -0.52 &    0.55
\end{array}


In [38]:
a2l.to_ltx(x, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
  -0.18 &  -0.67 &  -0.73 &    0.44 &    0.49 &    1.11 &    0.55
\end{array}


In [39]:
np.matmul(I, x)

array([ 0.,  0.,  0.,  5., 10., 10., 10.])

## Solve matrix I' using Crout's method for tridiagonal matrices

In [14]:
from lu.crout import crout_tridiagonal
import numpy as np

In [15]:
I_prime = np.array([[10, 5, 0, 0, 0, 0, 0],
                   [-1, 1, 1, 0, 0, 0, 0],
                   [0, 5, -3, 5, 0, 0, 0],
                   [0, 0, -1, -1, 1, 0, 0],
                   [0, 0, 0, 5, 1, 5, 0],
                   [0, 0, 0, 0, 1, -1, -1],
                   [0, 0, 0, 0, 0, 5, -10]])

In [16]:
I_prime

array([[ 10,   5,   0,   0,   0,   0,   0],
       [ -1,   1,   1,   0,   0,   0,   0],
       [  0,   5,  -3,   5,   0,   0,   0],
       [  0,   0,  -1,  -1,   1,   0,   0],
       [  0,   0,   0,   5,   1,   5,   0],
       [  0,   0,   0,   0,   1,  -1,  -1],
       [  0,   0,   0,   0,   0,   5, -10]])

In [17]:
a2l.to_ltx(I_prime, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
   10.00 &    5.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
  -1.00 &    1.00 &    1.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    5.00 &  -3.00 &    5.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &  -1.00 &  -1.00 &    1.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    5.00 &    1.00 &    5.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    1.00 &  -1.00 &  -1.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    5.00 & -10.00
\end{array}


In [18]:
L, U = crout_tridiagonal(7, I_prime)

In [20]:
a2l.to_ltx(L, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
   10.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
  -1.00 &    1.50 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    5.00 &  -6.33 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &  -1.00 &  -1.79 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    5.00 &    3.79 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    1.00 &  -2.32 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    5.00 & -12.16
\end{array}


In [21]:
a2l.to_ltx(U, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    1.00 &    0.50 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    1.00 &    0.67 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    1.00 &  -0.79 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    1.00 &  -0.56 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    1.00 &    1.32 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    1.00 &    0.43\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    1.00
\end{array}


In [23]:
b = np.array([10, 0, 10, 0, 5, 0, 10])

In [24]:
y, x = lu_solver(L, U, b, 7)

In [25]:
a2l.to_ltx(y, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    1.00 &    0.67 &  -1.05 &    0.59 &    0.54 &    0.23 &  -0.73
\end{array}


In [26]:
a2l.to_ltx(x, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    0.44 &    1.11 &  -0.67 &    0.49 &  -0.18 &    0.55 &  -0.73
\end{array}


In [21]:
np.matmul(I_prime, x)

array([ 1.00000000e+01,  0.00000000e+00,  1.00000000e+01, -5.55111512e-17,  5.00000000e+00,
        1.11022302e-16,  1.00000000e+01])

## Solve matrix I' using Doolitle's method

In [55]:
from lu.doolittle import doolittle
import numpy as np
from lu.solver import lu_solver

In [56]:
I_prime = np.array([[10, 5, 0, 0, 0, 0, 0],
                   [-1, 1, 1, 0, 0, 0, 0],
                   [0, 5, -3, 5, 0, 0, 0],
                   [0, 0, -1, -1, 1, 0, 0],
                   [0, 0, 0, 5, 1, 5, 0],
                   [0, 0, 0, 0, 1, -1, -1],
                   [0, 0, 0, 0, 0, 5, -10]])

In [57]:
I_prime

array([[ 10,   5,   0,   0,   0,   0,   0],
       [ -1,   1,   1,   0,   0,   0,   0],
       [  0,   5,  -3,   5,   0,   0,   0],
       [  0,   0,  -1,  -1,   1,   0,   0],
       [  0,   0,   0,   5,   1,   5,   0],
       [  0,   0,   0,   0,   1,  -1,  -1],
       [  0,   0,   0,   0,   0,   5, -10]])

In [58]:
L, U = doolittle(7, I_prime)

In [59]:
np.set_printoptions(linewidth=100)
print('L matrix:')
print(L)

print('U matrix')
print(U)

L matrix:
[[ 1.          0.          0.          0.          0.          0.          0.        ]
 [-0.1         1.          0.          0.          0.          0.          0.        ]
 [ 0.          3.33333333  1.          0.          0.          0.          0.        ]
 [ 0.          0.          0.15789474  1.          0.          0.          0.        ]
 [ 0.          0.         -0.         -2.79411765  1.          0.          0.        ]
 [ 0.          0.         -0.         -0.          0.26356589  1.          0.        ]
 [ 0.          0.         -0.         -0.          0.         -2.15719064  1.        ]]
U matrix
[[ 10.           5.           0.           0.           0.           0.           0.        ]
 [  0.           1.5          1.           0.           0.           0.           0.        ]
 [  0.           0.          -6.33333333   5.           0.           0.           0.        ]
 [  0.           0.           0.          -1.78947368   1.           0.           0.     

In [60]:
a2l.to_ltx(L, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    1.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
  -0.10 &    1.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    3.33 &    1.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.16 &    1.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &   -0.00 &  -2.79 &    1.00 &    0.00 &    0.00\\
    0.00 &    0.00 &   -0.00 &   -0.00 &    0.26 &    1.00 &    0.00\\
    0.00 &    0.00 &   -0.00 &   -0.00 &    0.00 &  -2.16 &    1.00
\end{array}


In [61]:
a2l.to_ltx(U, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
   10.00 &    5.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    1.50 &    1.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &  -6.33 &    5.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &  -1.79 &    1.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    3.79 &    5.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &  -2.32 &  -1.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00 & -12.16
\end{array}


In [62]:
b = np.array([10, 0, 10, 0, 5, 0, 10])

In [63]:
y, x = lu_solver(L, U, b, 7)

In [64]:
a2l.to_ltx(y, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
   10.00 &    1.00 &    6.67 &  -1.05 &    2.06 &  -0.54 &    8.83
\end{array}


In [65]:
a2l.to_ltx(x, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    0.44 &    1.11 &  -0.67 &    0.49 &  -0.18 &    0.55 &  -0.73
\end{array}


In [66]:
np.matmul(I_prime, x)

array([ 1.00000000e+01,  0.00000000e+00,  1.00000000e+01, -1.66533454e-16,  5.00000000e+00,
        0.00000000e+00,  1.00000000e+01])

## Solve matrix I' using Choleski method

In [2]:
from lu.choleski import choleski
from lu.solver import complex_lu_solver
import numpy as np

In [3]:
I_prime = np.array([[10, 5, 0, 0, 0, 0, 0],
                    [-1, 1, 1, 0, 0, 0, 0],
                    [0, 5, -3, 5, 0, 0, 0],
                    [0, 0, -1, -1, 1, 0, 0],
                    [0, 0, 0, 5, 1, 5, 0],
                    [0, 0, 0, 0, 1, -1, -1],
                    [0, 0, 0, 0, 0, 5, -10]])

In [4]:
I_prime

array([[ 10,   5,   0,   0,   0,   0,   0],
       [ -1,   1,   1,   0,   0,   0,   0],
       [  0,   5,  -3,   5,   0,   0,   0],
       [  0,   0,  -1,  -1,   1,   0,   0],
       [  0,   0,   0,   5,   1,   5,   0],
       [  0,   0,   0,   0,   1,  -1,  -1],
       [  0,   0,   0,   0,   0,   5, -10]])

In [5]:
L = choleski(7, I_prime)

In [6]:
U = np.transpose(L)

In [7]:
np.set_printoptions(linewidth=200)
print('L matrix:')
print(L)

print('U matrix:')
print(U)


L matrix:
[[ 3.16227766+0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j        ]
 [-0.31622777+0.j          0.9486833 +0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          1.05409255+0.j          0.        +2.02758751j  0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        -2.46598481j  2.25412535+0.j          0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j          0.44363105+0.j          0.89620951+0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j          0.        +0.j          5.57905259+0.j          0.        +5

In [8]:
for k in range(1):
    print(k)

0


In [39]:
b = np.array([10, 0, 10, 0, 5, 0, 10])

In [40]:
y, x = complex_lu_solver(L, U, b, 7)

In [41]:
y = np.linalg.solve(L, b)

In [42]:
np.linalg.solve(U, y)

array([ 1.06133295+0.j,  0.61332947+0.j,  0.44800347+0.j,  2.14613619+0.j, -0.09388118+0.j,  0.589549  +0.j, -1.0589549 -0.j])

In [43]:
np.matmul(L, U)

array([[ 10.+0.j,  -1.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j],
       [ -1.+0.j,   1.+0.j,   1.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j,   1.+0.j,  -3.+0.j,   5.+0.j,   0.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,   5.+0.j,  -1.+0.j,   1.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,   1.+0.j,   1.+0.j,   5.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   5.+0.j,  -1.+0.j,  -1.+0.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,   0.+0.j,  -1.+0.j, -10.+0.j]])

In [33]:
b_s = np.array(np.matmul(I_prime, x), dtype = np.float)

/Applications/anaconda3/envs/compu/lib/python3.5/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([ 1.36799768e+01, -1.11022302e-16,  1.24533179e+01, -2.68802084e+00,  1.35845448e+01,  3.75524721e-01,  1.35372940e+01])

## Solve matrix I' modified using Choleski method

In [67]:
from lu.choleski import choleski_modified
import numpy as np

In [68]:
I_prime_modified = np.array([[10, 5, 0, 0, 0, 0, 0],
                             [-1, 1, 1, 0, 0, 0, 0],
                             [0, -5, 3, -5, 0, 0, 0],
                             [0, 0, 1, 1, -1, 0, 0],
                             [0, 0, 0, 5, 1, 5, 0],
                             [0, 0, 0, 0, -1, 1, 1],
                             [0, 0, 0, 0, 0, -5, 10]])

In [69]:
I_prime_modified

array([[10,  5,  0,  0,  0,  0,  0],
       [-1,  1,  1,  0,  0,  0,  0],
       [ 0, -5,  3, -5,  0,  0,  0],
       [ 0,  0,  1,  1, -1,  0,  0],
       [ 0,  0,  0,  5,  1,  5,  0],
       [ 0,  0,  0,  0, -1,  1,  1],
       [ 0,  0,  0,  0,  0, -5, 10]])

In [70]:
a2l.to_ltx(I_prime_modified, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
   10.00 &    5.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
  -1.00 &    1.00 &    1.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &  -5.00 &    3.00 &  -5.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    1.00 &    1.00 &  -1.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    5.00 &    1.00 &    5.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &  -1.00 &    1.00 &    1.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &  -5.00 &   10.00
\end{array}


In [71]:
L, U = choleski_modified(7, I_prime_modified)

In [72]:
np.set_printoptions(linewidth=150)
print('L matrix:')
print(L)

print('U matrix: ')
print(U)

L matrix:
[[ 3.16227766  0.          0.          0.          0.          0.          0.        ]
 [-0.31622777  1.22474487  0.          0.          0.          0.          0.        ]
 [ 0.         -4.0824829   2.51661148  0.          0.          0.          0.        ]
 [ 0.          0.          0.39735971  1.33771211  0.          0.          0.        ]
 [ 0.          0.          0.          3.73772501  1.94784949  0.          0.        ]
 [ 0.          0.          0.          0.         -0.51338669  1.52244194  0.        ]
 [ 0.          0.          0.          0.          0.         -3.28419749  3.48671631]]
U matrix: 
[[ 3.16227766  1.58113883  0.          0.          0.          0.          0.        ]
 [ 0.          1.22474487  0.81649658  0.          0.          0.          0.        ]
 [ 0.          0.          2.51661148 -1.98679854  0.          0.          0.        ]
 [ 0.          0.          0.          1.33771211 -0.747545    0.          0.        ]
 [ 0.          0.    

In [73]:
a2l.to_ltx(L, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    3.16 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
  -0.32 &    1.22 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &  -4.08 &    2.52 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.40 &    1.34 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    3.74 &    1.95 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &  -0.51 &    1.52 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &  -3.28 &    3.49
\end{array}


In [74]:
a2l.to_ltx(U, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    3.16 &    1.58 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    1.22 &    0.82 &    0.00 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    2.52 &  -1.99 &    0.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    1.34 &  -0.75 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    1.95 &    2.57 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    1.52 &    0.66\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    3.49
\end{array}


In [75]:
b = np.array([10, 0, -10, 0, 5, 0, -10])

In [76]:
y, x = lu_solver(L, U, b, 7)

In [77]:
a2l.to_ltx(y, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    3.16 &    0.82 &  -2.65 &    0.79 &    1.06 &    0.36 &  -2.53
\end{array}


In [78]:
a2l.to_ltx(x, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    0.44 &    1.11 &  -0.67 &    0.49 &  -0.18 &    0.55 &  -0.73
\end{array}


In [78]:
np.matmul(L,U)

array([[10.,  5.,  0.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 0., -5.,  3., -5.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  1.,  5.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0., -5., 10.]])

In [61]:
a2l.to_ltx(I, frmt = '{:6.2f}', arraytype = 'array')

\begin{array}
    1.00 &  -1.00 &    0.00 &    0.00 &  -1.00 &    0.00 &    0.00\\
    0.00 &  -1.00 &    1.00 &    0.00 &  -1.00 &    0.00 &    1.00\\
    0.00 &    0.00 &    1.00 &  -1.00 &  -1.00 &    1.00 &    1.00\\
    0.00 &    0.00 &    0.00 &    1.00 &    6.00 &  -1.00 &    5.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    1.00 &    0.00 &    0.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &   15.00 & -50.00\\
    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &    0.00 &   65.00
\end{array}


In [8]:
suma1 = 0 
suma2 = 0
suma3 = 0
n = 7
for i in range(1, n-1):
    suma1 += 1
    timesj = 0
    for j in range(i + 1, n):
        suma2 += 1
        timesj += 1
        timesk = 0
        for k in range(i):
            timesk += 1
            suma3 += 1
        print(timesk)
    #print(timesj)

1
1
1
1
1
2
2
2
2
3
3
3
4
4
5


In [9]:
suma1

5

In [10]:
suma2

15

In [11]:
suma3

35

In [246]:
timesk

3

In [209]:
n = 8
suma = 0
for k in range(1, n):
       suma += 1
suma

7

In [234]:
suma = 0
suma2 = 0
n = 8
for i in range(1, n-1):
        #suma2 += 1 
        # L diagonal
        suma = 0
        for j in range(i + 1, n):
            suma += 1
            suma2 +=1
        print(suma)

6
5
4
3
2
1


In [235]:
suma

1

In [236]:
suma2

21

In [12]:
suma = 0
n = 7
for i in range(1, n-1):
    suma += 1

In [13]:
suma

5

In [46]:
n = 5
suma = 0
for i in range(1, n-1):
    suma += 1

In [47]:
suma

3

In [81]:
suma = 0
n = 80
for j in range(1, n):
    suma += 1

In [82]:
suma

79

In [89]:
suma = 0
n = 7

for i in range(1, n-1):
        z = 0
        for j in range(i+1, n):
            
            suma += 1

In [90]:
suma

15

In [93]:
suma = 0
n = 9

for k in range(n):
    suma += 1

In [94]:
suma

9

In [95]:
n = 7
suma = 0
for i in range(1, n-1):
    suma += 1

In [96]:
suma

5