# PEC 2

In [1]:
import sys
sys.path.append("..")
import sympy as sp
from sympy.plotting import plot as symplot
import pandas as pd
import numpy as np
from numpy import linspace
import matplotlib.pyplot as plt
from IPython.display import Math, Latex, Markdown

## Solve matrix I using Crout's method

In [2]:
from lu.lu import crout
import numpy as np

In [3]:
I = np.array([[1, -1, 0, 0, -1, 0, 0],
             [-1, 0, 1, 0, 0, 0, 1],
             [0, 1, 0, -1, 0, 1, 0],
             [1, 0, 0, 0, 5, 0, 5],
             [0, -3, 0, 0, 5, 5, 0],
             [0, 0, -10, 0, 0, 0, 5],
             [0, 0, 0, 10, 0, 5, 0]
             ])

In [4]:
I

array([[  1,  -1,   0,   0,  -1,   0,   0],
       [ -1,   0,   1,   0,   0,   0,   1],
       [  0,   1,   0,  -1,   0,   1,   0],
       [  1,   0,   0,   0,   5,   0,   5],
       [  0,  -3,   0,   0,   5,   5,   0],
       [  0,   0, -10,   0,   0,   0,   5],
       [  0,   0,   0,  10,   0,   5,   0]])

In [5]:
L, U = crout(7, I)

In [6]:
np.set_printoptions(linewidth=100)
print('L matrix:')
print(L)

print('U matrix')
print(U)

L matrix:
[[  1.           0.           0.           0.           0.           0.           0.        ]
 [ -1.          -1.           0.           0.           0.           0.           0.        ]
 [  0.           1.           1.           0.           0.           0.           0.        ]
 [  1.           1.           1.           1.           0.           0.           0.        ]
 [  0.          -3.          -3.          -3.          23.           0.           0.        ]
 [  0.           0.         -10.         -10.          50.         -10.86956522   0.        ]
 [  0.           0.           0.          10.         -60.          28.04347826  72.7       ]]
U matrix
[[ 1.         -1.          0.          0.         -1.          0.          0.        ]
 [ 0.          1.         -1.         -0.          1.         -0.         -1.        ]
 [ 0.          0.          1.         -1.         -1.          1.          1.        ]
 [ 0.          0.          0.          1.          6.        

## Solve matrix I' using Crout's method for tridiagonal matrices

In [8]:
from lu.lu import crout_tridiagonal
import numpy as np

In [9]:
I_prime = np.array([[10, 5, 0, 0, 0, 0, 0],
                   [-1, 1, 1, 0, 0, 0, 0],
                   [0, -5, 3, -5, 0, 0, 0],
                   [0, 0, -1, -1, 1, 0, 0],
                   [0, 0, 0, 5, 1, 5, 0],
                   [0, 0, 0, 0, -1, 1, 1],
                   [0, 0, 0, 0, 0, -5, 10]])

In [10]:
I_prime

array([[10,  5,  0,  0,  0,  0,  0],
       [-1,  1,  1,  0,  0,  0,  0],
       [ 0, -5,  3, -5,  0,  0,  0],
       [ 0,  0, -1, -1,  1,  0,  0],
       [ 0,  0,  0,  5,  1,  5,  0],
       [ 0,  0,  0,  0, -1,  1,  1],
       [ 0,  0,  0,  0,  0, -5, 10]])

In [11]:
L, U = crout_tridiagonal(7, I_prime)

In [12]:
np.set_printoptions(linewidth=100)
print('L matrix:')
print(L)

print('U matrix')
print(U)

L matrix:
[[10.          0.          0.          0.          0.          0.          0.        ]
 [-1.          1.5         0.          0.          0.          0.          0.        ]
 [ 0.         -5.          6.33333333  0.          0.          0.          0.        ]
 [ 0.          0.         -1.         -1.78947368  0.          0.          0.        ]
 [ 0.          0.          0.          5.          3.79411765  0.          0.        ]
 [ 0.          0.          0.          0.         -1.          2.31782946  0.        ]
 [ 0.          0.          0.          0.          0.         -5.         12.15719064]]
U matrix
[[ 1.          0.5         0.          0.          0.          0.          0.        ]
 [ 0.          1.          0.66666667  0.          0.          0.          0.        ]
 [ 0.          0.          1.         -0.78947368  0.          0.          0.        ]
 [ 0.          0.          0.          1.         -0.55882353  0.          0.        ]
 [ 0.          0.      

## Solve matrix I' using Doolitle's method

In [13]:
from lu.lu import doolittle
import numpy as np

In [14]:
I_prime = np.array([[10, 5, 0, 0, 0, 0, 0],
                   [-1, 1, 1, 0, 0, 0, 0],
                   [0, -5, 3, -5, 0, 0, 0],
                   [0, 0, -1, -1, 1, 0, 0],
                   [0, 0, 0, 5, 1, 5, 0],
                   [0, 0, 0, 0, -1, 1, 1],
                   [0, 0, 0, 0, 0, -5, 10]])

In [15]:
I_prime

array([[10,  5,  0,  0,  0,  0,  0],
       [-1,  1,  1,  0,  0,  0,  0],
       [ 0, -5,  3, -5,  0,  0,  0],
       [ 0,  0, -1, -1,  1,  0,  0],
       [ 0,  0,  0,  5,  1,  5,  0],
       [ 0,  0,  0,  0, -1,  1,  1],
       [ 0,  0,  0,  0,  0, -5, 10]])

In [16]:
L, U = doolittle(7, I_prime)

In [17]:
np.set_printoptions(linewidth=100)
print('L matrix:')
print(L)

print('U matrix')
print(U)

L matrix:
[[ 1.          0.          0.          0.          0.          0.          0.        ]
 [-0.1         1.          0.          0.          0.          0.          0.        ]
 [ 0.         -3.33333333  1.          0.          0.          0.          0.        ]
 [ 0.          0.         -0.15789474  1.          0.          0.          0.        ]
 [ 0.          0.          0.         -2.79411765  1.          0.          0.        ]
 [ 0.          0.          0.         -0.         -0.26356589  1.          0.        ]
 [ 0.          0.          0.         -0.          0.         -2.15719064  1.        ]]
U matrix
[[10.          5.          0.          0.          0.          0.          0.        ]
 [ 0.          1.5         1.          0.          0.          0.          0.        ]
 [ 0.          0.          6.33333333 -5.          0.          0.          0.        ]
 [ 0.          0.          0.         -1.78947368  1.          0.          0.        ]
 [ 0.          0.      